version: "3.2"

services:
  db:
    image: "redis:latest"
    volumes:
      - data:/data
    networks:
      dubdub:

  web:
    image: anoop/counter-app
    deploy:
      replicas: 10
    ports:
      - "8080"
    networks:
      - dubdub

networks:
  dubdub:
    driver: overlay

volumes:
  data:
