version: '2'
services:
  db:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - data:/data
    networks:
      - dubdub

  web:
    build: counter-app
    labels:
      - "interlock.hostname: web"
      - "interlock.domain: docker-training.com"
    ports:
      - "8080"
    networks:
      - dubdub

networks:
  dubdub:
    driver: overlay

volumes:
  data: {}
