version: "3.2"

services:
  db:
    image: "redis:latest"
    volumes:
      - data:/data
    networks:
      dubdub:
        aliases:
          - db

  web:
    image: anoop/counter-app
    ports:
      - "8080"
    networks:
      - dubdub

networks:
  dubdub:
    driver: overlay

volumes:
  data:
